name: Lint Code

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    - name: RuboCop
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rubocop
